name: foodgenius
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy>=1.20
  - pillow==10.2.0
  - scipy=1.12.0
  - pytorch=2.3.1
  - requests=2.26.0
  - tqdm=4.65.0
  - matplotlib=3.8.3
  - torchvision=0.18.0
  - pip:
      - kaggle
      - nvidia-cuda-runtime-cu12
      - bentoml==1.3.19
      - --extra-index-url=https://pypi.ngc.nvidia.com