apiVersion: v1
kind: Service
metadata:
  labels:
    app: foodgenius
  name: foodgenius
spec:
  ports:
  - name: predict
    port: 3000
    targetPort: 3000
  - name: metrics
    port: 3000
    targetPort: 3000
  selector:
    app: foodgenius
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: foodgenius
  name: foodgenius
spec:
  selector:
    matchLabels:
      app: foodgenius
  template:
    metadata:
      labels:
        app: foodgenius
    spec:
      containers:
      - image: david13356/foodgenius-service
        name: foodgenius
        ports:
        - containerPort: 3000
          name: metrics