apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    owner: bento
    release: prometheus
  name: bento-podmonitor
  namespace: default
spec:
  podMetricsEndpoints:
  - path: /metrics
    port: metrics
  selector:
    matchLabels: {}